# Generated by Django 2.1.5 on 2021-04-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="job_url",
            new_name="url",
        ),
    ]
