# Generated by Django 2.1.5 on 2021-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='topic',
        ),
        migrations.AddField(
            model_name='job',
            name='github_username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
