# Generated by Django 2.1.5 on 2021-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_auto_20210530_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
