# Generated by Django 2.1.5 on 2021-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="global_job_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
