# Generated by Django 2.1.5 on 2021-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_job_global_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
