# Generated by Django 2.1.5 on 2021-06-13 06:29

from django.db import migrations, models


def set_default_title_slug(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    for job in Job.objects.all():
        job.save()


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_auto_20210607_0837"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="title_slug",
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.RunPython(set_default_title_slug),
    ]
