  version: '3'
    
  services:
    web:
      build: .
      command: ./run-dev
      volumes:
        - .:/code
      ports:
        - "8000:8000"

    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres_password
        POSTGRES_USER: postgres
        POSTGRES_DB: diffblog
