#!/usr/bin/env bash
./manage.py runserver 0.0.0.0:8000 --settings=diffblog.dev_settings &
./manage.py rqworker --settings=diffblog.dev_settings following_bootstrapper followers_bootstrapper feed language_scanner follow_organizations &
npm run watch & redis-server
