#!/usr/bin/env bash
source bin/activate
./manage.py runserver --settings=diffblog.dev_settings &
./manage.py rqworker following_bootstrapper followers_bootstrapper feed language_scanner follow_organizations &
npm run watch
