recommended_blog_list = {
    "HackerNews": ["https://blog.ycombinator.com/feed/", ["Startups"]],
    "NickCraver": [
        "https://nickcraver.com/blog/",
        ["Web Development", "Distributed Systems"],
    ],
    "airbnb": [
        "https://medium.com/airbnb-engineering",
        [
            "Distributed Systems",
            "Machine Learning",
            "Web Development",
            "Design",
            "App Development",
            "Data Science",
            "Engineering Team Blogs",
        ],
    ],
    "antirez": ["http://antirez.com", ["Web Development"]],
    "coding-horror": ["https://blog.codinghorror.com/", ["Web Development"]],
    "coinbase": ["https://blog.coinbase.com/feed", ["Cryptocurrency"]],
    "danluu": [
        "https://danluu.com/",
        ["Computer Science Theory", "System Programming", "Hardware"],
    ],
    "deepmind": ["https://deepmind.com/blog/feed/basic/", ["Machine Learning"]],
    "dropbox": [
        "https://blogs.dropbox.com/tech/feed/",
        [
            "Web Development",
            "System Programming",
            "Hardware",
            "Distributed Systems",
            "Design",
            "App Development",
            "Engineering Team Blogs",
            "Networking",
        ],
    ],
    "ethereum": ["https://blog.ethereum.org/", ["Cryptocurrency", "Decentralized Web"]],
    "facebook": [
        "https://code.fb.com/feed/",
        [
            "Machine Learning",
            "Open Source",
            "Web Development",
            "Distributed Systems",
            "Design",
            "App Development",
            "Engineering Team Blogs",
            "Networking",
            "Programming Languages",
        ],
    ],
    "fastai": ["https://www.fast.ai/atom.xml", ["Machine Learning"]],
    "feross": [
        "https://feross.org/",
        ["Decentralized Web", "Open Source", "Javascript"],
    ],
}
