# Generated by Django 2.1.5 on 2019-02-11 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.TextField()),
                ('feed_url', models.CharField(max_length=200)),
                ('github_username', models.CharField(max_length=200)),
                ('github_id', models.IntegerField()),
                ('github_token', models.CharField(max_length=200, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200)),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
