# Generated by Django 2.1.5 on 2019-02-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190223_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blog_url_type',
            field=models.IntegerField(null=True),
        ),
    ]
