# Generated by Django 2.1.5 on 2019-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_blog_url_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_userprofile_following_+', to='app.UserProfile'),
        ),
    ]
