# Generated by Django 2.1.5 on 2019-03-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userprofile_feed_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='display_name',
        ),
    ]
