# Generated by Django 2.1.5 on 2019-03-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190316_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
