# Generated by Django 2.1.5 on 2019-03-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_userprofile_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='blog_url',
            new_name='website_url',
        ),
    ]
