# Generated by Django 2.1.5 on 2019-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190321_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blog_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
