# Generated by Django 2.1.5 on 2019-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='recommended',
            field=models.ManyToManyField(related_name='featured_in', to='app.UserProfile'),
        ),
    ]
