# Generated by Django 2.1.5 on 2019-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_topic_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='github_id',
            field=models.IntegerField(null=True),
        ),
    ]
