# Generated by Django 2.1.5 on 2019-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190323_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='recommended',
            field=models.ManyToManyField(related_name='reccomended_in', to='app.UserProfile'),
        ),
    ]
