# Generated by Django 2.1.5 on 2019-03-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190323_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(related_name='users', to='app.Topic'),
        ),
    ]
