# Generated by Django 2.1.5 on 2019-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190324_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
