# Generated by Django 2.1.5 on 2019-03-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_userprofile_fetched_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fetched_followers',
            new_name='fetched_following_users',
        ),
    ]
