# Generated by Django 2.1.5 on 2019-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190519_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pocket_api_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pocket_auto_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pocket_show_button',
            field=models.BooleanField(default=True),
        ),
    ]
