# Generated by Django 2.1.5 on 2019-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190522_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='recommended',
            field=models.ManyToManyField(related_name='recommended_in', to='app.UserProfile'),
        ),
    ]
