# Generated by Django 2.1.5 on 2019-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190529_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvotes_count',
            field=models.IntegerField(default=1),
        ),
    ]
