# Generated by Django 2.1.5 on 2020-04-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190629_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MirrorSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='aggregate_votes_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mirrorpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_posts', to='app.Post'),
        ),
        migrations.AddField(
            model_name='mirrorpost',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_posts', to='app.MirrorSource'),
        ),
    ]
