# Generated by Django 2.1.5 on 2020-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
