# Generated by Django 2.1.5 on 2020-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200516_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(3, 'Should be added by the user'), (2, 'No feed'), (10, 'Blog added'), (0, 'Pending'), (1, 'No GitHub account')], default=0),
        ),
    ]
