# Generated by Django 2.1.5 on 2020-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_blogsuggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(4, 'Non English blog'), (1, 'No GitHub account'), (2, 'No feed'), (0, 'Pending'), (3, 'Should be added by the user'), (10, 'Blog added')], default=0),
        ),
    ]
