# Generated by Django 2.1.5 on 2020-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200809_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_weekly_digest_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(10, 'Blog added'), (3, 'Should be added by the user'), (0, 'Pending'), (4, 'Non English blog'), (1, 'No GitHub account'), (2, 'No feed')], default=0),
        ),
    ]
