# Generated by Django 2.1.5 on 2020-10-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200927_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=150)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(4, 'Non English blog'), (0, 'Pending'), (3, 'Should be added by the user'), (2, 'No feed'), (10, 'Blog added'), (1, 'No GitHub account')], default=0),
        ),
    ]
