# Generated by Django 2.1.5 on 2020-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20201020_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_post_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (10, 'Blog added'), (3, 'Should be added by the user'), (4, 'Non English blog'), (2, 'No feed'), (1, 'No GitHub account')], default=0),
        ),
    ]
