# Generated by Django 2.1.5 on 2020-11-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20201104_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_photo_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (4, 'Non English blog'), (1, 'No GitHub account'), (2, 'No feed'), (10, 'Blog added'), (3, 'Should be added by the user')], default=0),
        ),
    ]
