# Generated by Django 2.1.5 on 2021-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20201108_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(3, 'Should be added by the user'), (10, 'Blog added'), (2, 'No feed'), (4, 'Non English blog'), (1, 'No GitHub account'), (0, 'Pending')], default=0),
        ),
    ]
