# Generated by Django 2.1.5 on 2021-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210308_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(3, 'Should be added by the user'), (0, 'Pending'), (2, 'No feed'), (10, 'Blog added'), (4, 'Non English blog'), (1, 'No GitHub account')], default=0),
        ),
    ]
