# Generated by Django 2.1.5 on 2021-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210420_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(10, 'Blog added'), (4, 'Non English blog'), (1, 'No GitHub account'), (0, 'Pending'), (3, 'Should be added by the user'), (2, 'No feed')], default=0),
        ),
    ]
