# Generated by Django 2.1.5 on 2021-04-26 06:32

import app.models
from django.db import migrations, models

def set_default_key(apps, schema_editor):
    UserProfile = apps.get_model('app', 'UserProfile')

    for profile in UserProfile.filter(unsubscribe_key=None):
        profile.unsubscribe_key = app.models.get_random_lowercase_string_of_50_chars()
        profile.save(update_fields=["unsubscribe_key"])

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20210425_1603'),
    ]

    operations = [
        migrations.RunPython(set_default_key),
        migrations.AlterField(
            model_name='userprofile',
            name='unsubscribe_key',
            field=models.CharField(default=app.models.get_random_lowercase_string_of_50_chars, max_length=50),
        ),
    ]
