# Generated by Django 2.1.5 on 2021-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210426_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(4, 'Non English blog'), (0, 'Pending'), (1, 'No GitHub account'), (3, 'Should be added by the user'), (10, 'Blog added'), (2, 'No feed')], default=0),
        ),
    ]
