# Generated by Django 2.1.5 on 2021-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20210509_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(3, 'Should be added by the user'), (0, 'Pending'), (10, 'Blog added'), (2, 'No feed'), (1, 'No GitHub account'), (4, 'Non English blog')], default=0),
        ),
    ]
