# Generated by Django 2.1.5 on 2021-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210509_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(3, 'Should be added by the user'), (1, 'No GitHub account'), (0, 'Pending'), (10, 'Blog added'), (2, 'No feed'), (4, 'Non English blog')], default=0),
        ),
    ]
