# Generated by Django 2.1.5 on 2021-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20210530_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(10, 'Blog added'), (1, 'No GitHub account'), (0, 'Pending'), (4, 'Non English blog'), (3, 'Should be added by the user'), (2, 'No feed')], default=0),
        ),
    ]
