# Generated by Django 2.1.5 on 2021-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20210530_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(10, 'Blog added'), (3, 'Should be added by the user'), (1, 'No GitHub account'), (4, 'Non English blog'), (2, 'No feed'), (0, 'Pending')], default=0),
        ),
    ]
