# Generated by Django 2.1.5 on 2021-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20210606_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (4, 'Non English blog'), (3, 'Should be added by the user'), (2, 'No feed'), (10, 'Blog added'), (1, 'No GitHub account')], default=0),
        ),
    ]
