# Generated by Django 2.1.5 on 2021-06-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20210607_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(4, 'Non English blog'), (2, 'No feed'), (10, 'Blog added'), (1, 'No GitHub account'), (0, 'Pending'), (3, 'Should be added by the user')], default=0),
        ),
    ]
