# Generated by Django 2.1.5 on 2021-06-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20210613_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (2, 'No feed'), (4, 'Non English blog'), (10, 'Blog added'), (1, 'No GitHub account'), (3, 'Should be added by the user')], default=0),
        ),
    ]
