# Generated by Django 2.1.5 on 2021-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20210626_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsuggestion',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'No GitHub account'), (2, 'No feed'), (3, 'Should be added by the user'), (4, 'Non English blog'), (10, 'Blog added')], default=0),
        ),
    ]
