# Generated by Django 2.1.5 on 2021-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_userprofile_plugin_public_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cleaned_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.IntegerField(default=1),
        ),
    ]
