# Generated by Django 2.1.5 on 2021-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_userprofile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirrorpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
