# Generated by Django 2.1.5 on 2022-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20220306_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
