# Generated by Django 2.1.5 on 2022-06-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_topic_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubcampaign',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
