# Generated by Django 2.1.5 on 2023-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_githubcampaign_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
