# Generated by Django 2.1.5 on 2019-12-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='timestamp',
            new_name='date',
        ),
    ]
